---
- name: Prepare all hosts
  hosts: all
  collections:
    - jmd_collection.home_stack
    - community.docker
  gather_facts: true
  vars_files:
    - ./secret.yml
  roles:
    - role: common
    - role: raspberrypi-config
    - role: docker-install
    - role: docker-containers/portainer-agent
  tags:
    - core

- name: Install DNS servers
  hosts: dns
  collections:
    - community.docker
  gather_facts: true
  vars_files:
    - ./secret.yml
  roles:
    - role: docker-containers/adguardhome
  tags:
    - dns
#############
#    NAS    #
#############

- name: Install NAS services
  hosts: nas
  become: true
  collections:
    - community.docker
  gather_facts: false
  vars_files:
    - ./secret.yml
  roles:
    - role: docker-containers/plex
    - role: docker-containers/nextcloud
    - role: docker-containers/cloudflared-ddns
    - role: docker-containers/adguardhome
    - role: docker-containers/portainer
    - role: docker-containers/http-services/dashy
    - role: docker-containers/http-services/traefik
      tags:
        - proxy
  post_tasks:
    - name: Create network for http-services
      community.docker.docker_network:
        enable_ipv6: false
        driver: bridge
        ipam_config:
          - iprange: "{{ nas_proxy_net_ip_range }}"
            subnet: "{{ nas_proxy_net_ip_range }}"
        ipam_driver: default
        name: "{{ nas_proxy_net }}"
        connected:
          - "{{ nextcloud_container_name }}"
          - "{{ dashy_container_name }}"
          - "{{ adguardhome_container_name }}"
          - "{{ portainer_container_name }}"
          - "{{ traefik_container_name }}"
      tags:
        - proxy
############
#  HASSIO  #
############

- name: Install Home Assistant
  hosts: hassio
  gather_facts: false
  become: true
  roles:
    - role: homeassistant
