ansible_ssh_user: pi
ansible_python_interpreter: /usr/bin/python3
ansible_host: "{{ vault_hassio_ip }}"

# common
common_hostname: "{{ vault_hassio_hostname }}"
common_host_location: office

# raspberrypi-config
enable_ssh: 0
enable_vnc: 1
enable_overscan: 0
enable_camera: 1
enable_wifi: false
enable_network_boot_wait: 0
expand_rootfs: false
raspi_reboot_timeout: 180
gpu_mem: 128

# cadvisor
cadvisor_mode: "remote"

# nodeexporter
nodeexporter_mode: "remote"
