---
- name: Create Directories for Wireguard
  ansible.builtin.file:
      path: "{{ docker_data_dir }}/{{ service_name }}/{{ wireguard_container_name }}/{{ item }}"
      state: directory
      mode: "0755"
  loop: "{{ wireguard_dirs }}"

- name: Deploy Wireguard
  docker_container:
      name: "{{ wireguard_container_name }}"
      image: "linuxserver/wireguard:latest"
      hostname: "{{ wireguard_container_name }}"
      pull: true
      state: started
      capabilities:
          - NET_ADMIN
          - SYS_MODULE
      env:
          SERVERPORT: "{{ wireguard_port }}"
          TZ: "{{ common_timezone }}"
          SERVERURL: "{{ wireguard_ddns_name }}"
          PEERS: "{{ wireguard_no_peers }}"
          PEERDNS: "{{ common_dns }}"
      volumes:
          - "{{ docker_data_dir }}/{{ service_name }}/{{ wireguard_container_name }}/config:/config"
          - "/lib/modules:/lib/modules"
      sysctls:
          "net.ipv4.conf.all.src_valid_mark": 1
      dns_servers:
          - "{{ common_dns }}"
      ports:
          - "{{ wireguard_port }}:{{ wireguard_port }}/udp"
      restart_policy: always
