---
- name: Deploy Portainer Agent
  docker_container:
      name: "{{ portainer_agent_container_name }}"
      image: "portainer/agent:latest"
      hostname: "{{ portainer_agent_container_name }}"
      pull: true
      state: started
      ports:
          - "{{ portainer_agent_port }}:9001"
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"
      restart_policy: unless-stopped
