---
- name: Restart {{ service_name }}
  docker_container:
    state: started
    restart: true
    name: "{{ adguardhome_container_name }}"
  listen: "restart adguardhome"

- name: Reload systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: reloaded
  become: true
  listen: "reload systemd"

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  become: true
  listen: "restart systemd"
