ansible_ssh_user: pi
ansible_python_interpreter: /usr/bin/python3
# ansible_host: 1.1.1.10

# common
common_hostname: ckaccess
common_host_location: office

# raspberrypi-config
enable_ssh: 0
enable_vnc: 1
enable_overscan: 0
enable_camera: 1
enable_wifi: false
enable_network_boot_wait: 0
expand_rootfs: false
raspi_reboot_timeout: 360
gpu_mem: 32