---
- name: Create Directories for Dashy
  ansible.builtin.file:
      path: "{{ docker_data_dir }}/{{ service_name }}/{{ pialert_container_name }}/{{ item }}"
      state: directory
      mode: "0755"
  loop: "{{ pialert_dirs }}"

- name: Deploy Dashy
  docker_container:
      name: "{{ pialert_container_name }}"
      image: "jokobsk/pi.alert:latest"
      hostname: "{{ pialert_container_name }}"
      pull: true
      state: started
      volumes:
          - "{{ docker_data_dir }}/{{ service_name }}/{{ pialert_container_name }}/config:/home/pi/pialert/config"
      restart_policy: unless-stopped
