- name: Deploy cAdvisor
  docker_container:
    name: "{{ cadvisor_container_name }}"
    image: "gcr.io/cadvisor/cadvisor:v0.47.1"
    privileged: true
    hostname: "{{ cadvisor_container_name }}"
    pull: true
    restart_policy: "unless-stopped"
    state: started
    devices:
      - "/dev/kmsg:/dev/kmsg"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
    labels:
      org.label-schema.group: "monitoring"
