service_name: grafana
grafana_container_name: grafana
grafana_port: 3000
grafana_admin_user: admin
grafana_admin_pass: admin
grafana_dirs:
  - data
  - provisioning
  - provisioning/dashboards
  - provisioning/datasources
